dist: trusty
conditions: v1

language: node_js

env:
- FOO=foo
- FOO=bar

node_js:
- 'lts/*'

install:
- npm i
- npm ci --prefix packages/core

cache:
  directories:
  - "$HOME/.npm"

script:
- npm run package --prefix packages/core

jobs:
  include:
    - stage: release
      if: |
        repo = 'Mogztter/demo-npm-meta-package' AND \
        tag IS present
      script:
        - ./scripts/package.sh
        - ./scripts/publish.sh
      deploy:
        - provider: releases
          api_key: ${GITHUB_TOKEN}
          file: packages/core/bin/demo-npm-meta-package.dist.*
          skip_cleanup: true
          file_glob: true
          on:
            tags: true
